### ISSUE TITLE
Change end Game Squence

### ISSUE THREAD

**Issue by BeanSparrow** [sc0ttr0berts0n/tunk#12]
- [x] Fade all to greyscale, except player blood.
 - [x] Display Final Score
 - [x] Offer reset to play again

**Comment by sc0ttr0berts0n** [comment]
if it were up to me, I would visually offer reset (that doesn't work yet), and make the reset the game feature a separate task. its much more complicated than the other two tasks @BeanSparrow.

**Comment by sc0ttr0berts0n** [comment]
is WIP via #13
