### ISSUE TITLE
Player score rapidly increases when repairing sometimes

### ISSUE THREAD

**Issue by sc0ttr0berts0n** [sc0ttr0berts0n/tunk#5]
it appears to be tied to shots coming in through the area, but I'm not sure if I have any more to go on. I think the best solution is to implement a more robust or alternative method of awarding points.

**Comment by BeanSparrow** [comment]
I am considering dissociating the score from the player repair mechanics and instead associating it with the wall texture swap.

**Comment by BeanSparrow** [comment]
submitted a pull request on a branch that solves this issue by changing score counting to wall texture change rather than health value.

**Comment by sc0ttr0berts0n** [comment]
Merged #6 , Thanks. Closed!

**Comment by sc0ttr0berts0n** [comment]
I just tested a feature (which worked fine)...but my final score: `99`. So this is still happening

**Comment by sc0ttr0berts0n** [comment]
After more testing, it looks like I was wrong or viewing an incorrect version..its dead..for now
